name: Build and Deploy NestJS to CapRover

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy_via_cli:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install CapRover CLI
        run: npm i -g caprover

      - name: Deploy to CapRover via CLI (non-interactive)
        env:
          CAPROVER_URL: ${{ secrets.CAPROVER_SERVER }}
          CAPROVER_APP: ${{ secrets.APP_NAME }}
          CAPROVER_TOKEN: ${{ secrets.APP_TOKEN }}
        run: |
          npm i -g caprover
          caprover deploy \
            --caproverUrl="$CAPROVER_URL" \
            --appName="$CAPROVER_APP" \
            --appToken="$CAPROVER_TOKEN" \
            --branch="main"
